### PR TITLE
Use proper punctuation marks in prose

### PR DESCRIPTION
**Pull request by csswizardry**
The text of the book itself was using dumb quotes (i.e. " and ') which
I have replaced with proper book quotes (i.e. ‘’, “”). There were also
lots of hyphens which I have replaced with spaced en dashes.

Further reading: csswizardry.com/2017/02/typography-for-developers

### CODE REVIEW

**Comment by addyosmani** [comment]
@csswizardry Thanks for the PR to introduce proper book quotes and en-dashes into the text! Changes here LGTM. 

Could you complete the above to make @googlebot happy and I can go ahead and merge this in? :)

**Comment by neonick** [comment]
Awesome work, @csswizardry! I thought to do the same. Thank you!

**Comment by csswizardry** [comment]
I signed it!

**Comment by addyosmani** [comment]
@csswizardry Perfect. One last request - could we rebase against master? If tight on time I'll manually do that next week.

**Pull request merged**
